# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Character.create(character: 'A', character_distance: 0.008)
Character.create(character: 'B', character_distance: 0.012)
Character.create(character: 'C', character_distance: 0.007)
Character.create(character: 'D', character_distance: 0.009)
Character.create(character: 'E', character_distance: 0.009)
Character.create(character: 'F', character_distance: 0.007)
Character.create(character: 'G', character_distance: 0.012)
Character.create(character: 'H', character_distance: 0.008)
Character.create(character: 'I', character_distance: 0.003)
Character.create(character: 'J', character_distance: 0.004)
Character.create(character: 'K', character_distance: 0.008)
Character.create(character: 'L', character_distance: 0.005)
Character.create(character: 'M', character_distance: 0.012)
Character.create(character: 'N', character_distance: 0.010)
Character.create(character: 'O', character_distance: 0.009)
Character.create(character: 'P', character_distance: 0.007)
Character.create(character: 'Q', character_distance: 0.011)
Character.create(character: 'R', character_distance: 0.009)
Character.create(character: 'S', character_distance: 0.009)
Character.create(character: 'T', character_distance: 0.005)
Character.create(character: 'U', character_distance: 0.006)
Character.create(character: 'V', character_distance: 0.006)
Character.create(character: 'W', character_distance: 0.012)
Character.create(character: 'X', character_distance: 0.007)
Character.create(character: 'Y', character_distance: 0.006)
Character.create(character: 'Z', character_distance: 0.010)
Character.create(character: 'a', character_distance: 0.007)
Character.create(character: 'b', character_distance: 0.009)
Character.create(character: 'c', character_distance: 0.005)
Character.create(character: 'd', character_distance: 0.009)
Character.create(character: 'e', character_distance: 0.007)
Character.create(character: 'f', character_distance: 0.004)
Character.create(character: 'g', character_distance: 0.009)
Character.create(character: 'h', character_distance: 0.006)
Character.create(character: 'i', character_distance: 0.003)
Character.create(character: 'j', character_distance: 0.003)
Character.create(character: 'k', character_distance: 0.006)
Character.create(character: 'l', character_distance: 0.003)
Character.create(character: 'm', character_distance: 0.007)
Character.create(character: 'n', character_distance: 0.005)
Character.create(character: 'o', character_distance: 0.006)
Character.create(character: 'p', character_distance: 0.008)
Character.create(character: 'q', character_distance: 0.008)
Character.create(character: 'r', character_distance: 0.003)
Character.create(character: 's', character_distance: 0.007)
Character.create(character: 't', character_distance: 0.004)
Character.create(character: 'u', character_distance: 0.005)
Character.create(character: 'v', character_distance: 0.004)
Character.create(character: 'w', character_distance: 0.008)
Character.create(character: 'x', character_distance: 0.006)
Character.create(character: 'y', character_distance: 0.005)
Character.create(character: 'z', character_distance: 0.006)


